### ISSUE TITLE
Python :))

### ISSUE THREAD

**Issue by Donkere-vader** [ContributaryCommunity/topology#15]
## Type of Change
- [x] New Language
- [ ] New Project
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

It would be nice if python would be a supported language

**Comment by thescientist13** [comment]
completely missed this, thanks for the suggestion!  Any good projects you would recommend to get things started?

**Comment by Donkere-vader** [comment]
maybe [django](https://github.com/django) (A very popular backend framework)
or [python](https://github.com/python) itself

**Comment by thescientist13** [comment]
Thanks again for the suggestion!  

I've added Python and those projects and you can see them live on the site now.  😃 
https://www.contributary.community/
<img width="1173" alt="Screen Shot 2021-05-20 at 10 31 34 AM" src="https://user-images.githubusercontent.com/895923/118997472-af0b2000-b956-11eb-99cd-6e554f58baa5.png">

Feel free suggest or contribute any more languages / projects you have!
